# Generated by Django 3.2.12 on 2022-04-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arranger', '0004_delete_phonemodel_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='arranger.service'),
        ),
    ]
